---
name: docker_build_test
run-name: docker_build

on:
  workflow_dispatch:

  pull_request:

env:
  DOCKER_FILE_PATH: docker/
  IMAGE_NAME: hasib-test-image
  IMAGE_TAG: arm32v7

jobs:
  docker_build:
    runs-on: ubuntu-latest
    outputs:
      build_image: ${{ steps.build.outputs.build_image }}
    steps:

      - name: Clone test-docker-build-2 repository
        id: clone
        run: |
          pwd
          git clone https://github.com/hasiburr-qti/test-docker-build-2.git
          ls
        env:
          GITHUB_TOKEN: ${{ secrets.HASIB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install Docker system in the runner
        uses: ./.github/actions/install-docker

      - name: Build the Docker image
        id: build
        run: |
          # Build the docker image
          set -eux
          pwd
          ls
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} test-docker-build-2/${{ env.DOCKER_FILE_PATH }}

          echo "Build successful for image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "build_image=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> "$GITHUB_OUTPUT"

          set +eux

      - name: Push to docker registry
        run: |
          echo "::Push Successful::"

  publish:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Notify User
        run: |
          echo "Docker image build successful: Image tag=${{ needs.docker_build.outputs.build_image }}"
